def callChildJob(checkJobBuildable) {
    stage('cENM Manage And Supervise Network') {
        if (checkJobBuildable("cENM_Manage_And_Supervise_Network")) {
            def Cenm_Manage_And_Supervise_Network = build(
                job: "cENM_Manage_And_Supervise_Network",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'supervision_types', value: env.supervision_types),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'test_phase', value: env.test_phase),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Manage_And_Supervise_Network Job is disabled. So skipping"
        }
    }
}

return this
