def returnParametersForDsl() {
    return [REGULAR_SLAVES: env.REGULAR_SLAVES, OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfSpinnakerCenmCbrsDcsaUpgradeJobs() {
    def listOfSpinnakerCenmCbrsDcsaUpgradeJobs = []

    // === Spinnaker cENM CbrsDcsa Upgrade Pipeline Updater ===
    listOfSpinnakerCenmCbrsDcsaUpgradeJobs = listOfSpinnakerCenmCbrsDcsaUpgradeJobs.plus('DSL/spinnakerpipeline/cenm/cbrs_dcsa_upgrade/SpinnakerCenmCbrsDcsaUpgradePipeline.groovy')

    // === Spinnaker cENM CbrsDcsa Upgrade Pipeline Generator Updater ===
    listOfSpinnakerCenmCbrsDcsaUpgradeJobs = listOfSpinnakerCenmCbrsDcsaUpgradeJobs.plus('pipeline_generation/spinnaker/cbrs_dcsa_upgrade/DSL/SpinnakerCenmCbrsDcsaUpgradePipelineUpdater.groovy')

    return listOfSpinnakerCenmCbrsDcsaUpgradeJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.REGULAR_SLAVES == null
                    }
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker cENM Cbrs Dcsa Upgrade Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfSpinnakerCenmCbrsDcsaUpgradeJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}