def callChildJob(checkJobBuildable) {
    stage('cENM Apply Priority 1 Workload') {
        if (checkJobBuildable("cENM_Apply_Priority_1_Workload")) {
            def Cenm_Apply_Priority_1_Workload = build(
                job: "cENM_Apply_Priority_1_Workload",
                propagate: false,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'workload_profiles', value: env.workload_profiles),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'test_phase', value: env.test_phase),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Apply_Priority_1_Workload Job is disabled. So skipping"
        }
    }
}

return this
