def callChildJob(checkJobBuildable) {
    stage('cENM Add Prepop Nodes for RFA250') {
        if (checkJobBuildable("cENM_Add_Prepopulated_Nodes_Functional")) {
            def Cenm_Add_Prepopulated_Nodes_Functional = build(
                job: "cENM_Add_Prepopulated_Nodes_Functional",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'test_phase', value: env.test_phase),
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'drop', value: env.drop),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'central_csv_version', value: env.central_csv_version),
                    string(name: 'product_set_version', value: env.product_set_version),
                ]
            )
        } else {
            echo "cENM_Add_Prepopulated_Nodes_Functional Job is disabled. So skipping"
        }
    }
}

return this
