def returnParametersForDsl() {
    return [TE_DOCKER_SLAVES: env.TE_DOCKER_SLAVES, OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfCenmCapoUpgradeJobs() {
    def listOfCenmCapoUpgradeJobs = []

    // === cENM CAPO Upgrade Spinnaker Pipeline Standalone Job ===
    listOfCenmCapoUpgradeJobs = listOfCenmCapoUpgradeJobs.plus('DSL/spinnakerpipeline/cenm/capo_upgrade/SpinnakerCenmCapoPipelineUpgradeUpdater.groovy')

    // === cENM CAPO Upgrade Spinnaker Pipeline Updater ===
    listOfCenmCapoUpgradeJobs = listOfCenmCapoUpgradeJobs.plus('pipeline_generation/spinnaker/capo_upgrade/DSL/spinnakercenmcapoupgradepipelineupdater/SpinnakerCenmCapoUpgradePipelineUpdater.groovy')

    return listOfCenmCapoUpgradeJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.TE_DOCKER_SLAVES == null
                    }
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker CAPO Upgrade Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfCenmCapoUpgradeJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}
