def commonMethods

pipeline {
    agent {
        node {
            label SLAVE
        }
    }
    options {
        timestamps()
    }
    stages {
        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Sending Confidence Level for ${to_ps}"
                    currentBuild.description = "<b>Confidence Level Name = ${usecase}<br>Confidence Level Status = ${usecase_status}</b>"
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Sending Confidence Level') {
            steps{
                sh 'MTELoopScripts/pipeline_scripts/cenm_send_confidence_level_to_buildlog_setup.sh ${WORKSPACE}/parameters.properties || exit 1'
            }
        }
    }
}
