def commonMethods

pipeline {
    agent {
        node {
            label SLAVE
        }
    }
    options {
        timestamps()
    }

    stages {
        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Adu on ${cluster_id}"
                    currentBuild.description = "<b>Drop = ${drop}<br>Product Set Version = ${cenm_product_set_version}<br>MT Utils Version = ${mt_utils_version}</b>"
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('cENM Send Confidence Level') {
            steps {
                setConfidenceLevelToSend('in_progress');
            }
        }

        stage('cENM Send Confidence Level to Build log') {
            steps {
                setConfidenceLevelToSendToBuildLog('in_progress', 'in_progress','update', '', '');
            }
        }

        stage('Resolve Availability Watcher Version') {
            steps {
                sh "sh MTELoopScripts/pipeline_scripts/cenm_adu_flow_setup.sh ${WORKSPACE}/parameters.properties || exit 1"
            }
        }

        stage('Inject environment variables') {
            steps {
                script {
                    commonMethods.loadProperties("${WORKSPACE}/build.properties")
                }
            }
        }

        stage('cENM Test ADU') {
            steps {
                script {
                    if (env.is_network_type_STC == 'true') {
                        if (checkJobBuildable("cENM_STC_Test_ADU")) {
                            def Cenm_STC_Test_ADU = build(
                                job: "cENM_STC_Test_ADU",
                                propagate: true,
                                wait: true,
                                parameters: [
                                    string(name: 'cluster_id', value: env.cluster_id),
                                    string(name: 'test_phase', value: env.test_phase),
                                    string(name: 'product_set_version', value: env.cenm_product_set_version),
                                    string(name: 'drop', value: env.drop),
                                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                                    string(name: 'taf_version', value: env.taf_version),
                                    string(name: 'adu_version', value: env.adu_version),
                                    string(name: 'availability_watcher_version', value: env.availability_watcher_version),
                                    string(name: 'cENM_Upgrade_Type', value: 'ENM'),
                                    string(name: 'CCD_ADU_Duration_Selector',  value: '0'),
                                    string(name: 'adu_coverage_selector',  value: env.adu_coverage_selector)
                                ]
                            )
                        } else {
                            echo "cENM_STC_Test_ADU Job is disabled. So skipping"
                        }
                    } else {
                        if (checkJobBuildable("cENM_Test_ADU")) {
                            def Cenm_Test_ADU = build(
                                job: "cENM_Test_ADU",
                                propagate: false,
                                wait: true,
                                parameters: [
                                    string(name: 'cluster_id', value: env.cluster_id),
                                    string(name: 'test_phase', value: env.test_phase),
                                    string(name: 'deployment_mechanism', value: env.deployment_mechanism),
                                    string(name: 'product_set_version', value: env.cenm_product_set_version),
                                    string(name: 'drop', value: env.drop),
                                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                                    string(name: 'taf_version', value: env.taf_version),
                                    string(name: 'adu_version', value: env.adu_version),
                                    string(name: 'availability_watcher_version', value: env.availability_watcher_version),
                                    string(name: 'cENM_Upgrade_Type', value: env.cENM_Upgrade_Type),
                                    string(name: 'CCD_ADU_Duration_Selector',  value: env.CCD_ADU_Duration_Selector),
                                    string(name: 'adu_coverage_selector',  value: env.adu_coverage_selector)
                                ]
                            )
                            env.aduBuildVariables = Cenm_Test_ADU.getBuildVariables()
                            env.allureLogUrl = sh(script: 'echo "${aduBuildVariables}" | tr "," "\n" | grep "TE_ALLURE_LOG_URL" | xargs | cut -d "=" -f 2', returnStdout: true)
                            if (Cenm_Test_ADU.result != "SUCCESS") {
                                echo "ERROR : Cenm_Test_ADU failed. Failing the build!"
                                currentBuild.result = 'FAILURE'
                            }
                        } else {
                            echo "cENM_Test_ADU Job is disabled. So skipping"
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            setConfidenceLevelToSend('passed');
            setConfidenceLevelToSendToBuildLog('in_progress', 'passed','update', '', env.allureLogUrl);
        }
        failure {
            setConfidenceLevelToSend('failed');
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', '', env.allureLogUrl);
        }
        aborted {
            setConfidenceLevelToSend('failed');
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', '', '');
        }
    }
}

def setConfidenceLevelToSend(confidence_level_status) {
    script {
        if (env.send_confidence_level == 'YES' && env.test_phase == 'MTE') {
            if (env.deployment_utilities && confidence_level_status != "in_progress") {
                if (checkJobBuildable("cENM_Send_Confidence_Level")) {
                    def Cenm_Send_Confidence_Level = build(
                        job: "cENM_Send_Confidence_Level",
                        propagate: false,
                        wait: false,
                        parameters: [
                            string(name: 'product_set_version', value: env.cenm_product_set_version),
                            string(name: 'confidence_level_name', value: 'cENM-UG-Availability'),
                            string(name: 'confidence_level_status', value: confidence_level_status),
                            string(name: 'deployment_utilities', value: env.deployment_utilities),
                        ]
                    )
                } else {
                    echo "cENM_Send_Confidence_Level Job is disabled. So skipping"
                }
            } else {
                if (checkJobBuildable("cENM_Send_Confidence_Level")) {
                    def Cenm_Send_Confidence_Level = build(
                        job: "cENM_Send_Confidence_Level",
                        propagate: false,
                        wait: false,
                        parameters: [
                            string(name: 'product_set_version', value: env.cenm_product_set_version),
                            string(name: 'confidence_level_name', value: 'cENM-UG-Availability'),
                            string(name: 'confidence_level_status', value: confidence_level_status),
                        ]
                    )
                } else {
                    echo "cENM_Send_Confidence_Level Job is disabled. So skipping"
                }
            }
        }
    }
}

def setConfidenceLevelToSendToBuildLog(overall_status, confidence_level_status, build_action, job_link, allure_link) {
    script {
        if (env.publish_to_buildlog == 'YES' && env.test_phase == 'MTE') {
            if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                if (env.is_dit_versioning_applied == 'True') {
                    env.usecase = 'cENM-Deploy-UG-CSAR-Lite'
                } else {
                    env.usecase = 'cENM-Deploy-UG-Charts'
                }
                def Cenm_Send_Confidence_Level_To_Build_Log = build(
                    job: "cENM_Send_Confidence_Level_To_Build_Log",
                    propagate: false,
                    wait: false,
                    parameters: [
                        string(name: 'drop', value: env.drop),
                        string(name: 'to_ps', value: env.cenm_product_set_version),
                        string(name: 'build_log_action', value: build_action),
                        string(name: 'usecase_status', value: overall_status),
                        string(name: 'deployment', value: env.cluster_id),
                        string(name: 'test_phase', value: env.test_phase),
                        string(name: 'usecase', value: env.usecase),
                        string(name: 'confidence_level', value: 'cENM-UG-Availability'),
                        string(name: 'allure_link', value: allure_link ),
                        string(name: 'status', value: confidence_level_status),
                        string(name: 'timestamp', value: ''),
                        string(name: 'mt_utils_version', value: env.mt_utils_version)
                    ]
                )
            } else {
                echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
            }
        }
        else {
            if (env.publish_to_buildlog == 'YES' && env.test_phase == 'CDL') {
                if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                    def Cenm_Send_Confidence_Level_To_Build_Log = build(
                        job: "cENM_Send_Confidence_Level_To_Build_Log",
                        propagate: false,
                        wait: false,
                        parameters: [
                            string(name: 'drop', value: env.drop),
                            string(name: 'to_ps', value: env.cenm_product_set_version),
                            string(name: 'build_log_action', value: build_action),
                            string(name: 'usecase_status', value: overall_status),
                            string(name: 'deployment', value: env.cluster_id),
                            string(name: 'test_phase', value: env.test_phase),
                            string(name: 'usecase', value: 'cENM-Deploy-UG-CSAR'),
                            string(name: 'confidence_level', value: 'cENM-UG-Availability'),
                            string(name: 'allure_link', value: allure_link ),
                            string(name: 'status', value: confidence_level_status),
                            string(name: 'timestamp', value: ''),
                            string(name: 'mt_utils_version', value: env.mt_utils_version)
                        ]
                    )
                } else {
                    echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
                }
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}