def commonMethods

pipeline {
    agent {
        node {
            label SLAVE
        }
    }
    options {
        timestamps()
    }
    stages {
        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Set build descriptions') {
            steps {
                script {
                    currentBuild.displayName = "Geo Secondary Site Setup on ${cluster_id}"
                    currentBuild.description = "<b>MT Utils Version = ${mt_utils_version}<br>non_critical_data_list = ${non_critical_data_list}</b>"
                }
            }
        }

        stage('Running Setup Script') {
            steps{
                timeout(time: 720, unit: 'MINUTES') {
                    sh "sh MTELoopScripts/pipeline_scripts/geo_secondary_setup.sh ${WORKSPACE}/parameters.properties || exit 1"
                }
            }
        }
    }
}

