def returnParametersForDsl() {
    return [OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfSpinnakerCenmNetworkAndWorkloadSetupJobs() {
    def listOfSpinnakerCenmNetworkAndWorkloadSetupJobs = []

    // === Network And Workload Setup Spinnaker Pipeline Updater ===
    listOfSpinnakerCenmNetworkAndWorkloadSetupJobs = listOfSpinnakerCenmNetworkAndWorkloadSetupJobs.plus('DSL/spinnakerpipeline/cenm/network_and_workload_setup/de/SpinnakerCenmPipelineNetworkAndWorkloadSetupUpdater.groovy')

    // === Spinnaker Network And Workload Setup Pipeline Generator Updater ===
    listOfSpinnakerCenmNetworkAndWorkloadSetupJobs = listOfSpinnakerCenmNetworkAndWorkloadSetupJobs.plus('pipeline_generation/spinnaker/network_and_workload_setup/de/DSL/spinnakercenmnetworkandworkloadsetuppipelineupdater/SpinnakerCenmNetworkAndWorkloadSetupPipelineUpdater.groovy')

    return listOfSpinnakerCenmNetworkAndWorkloadSetupJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker cENM Network And Workload Setup Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfSpinnakerCenmNetworkAndWorkloadSetupJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}