def callChildJob(checkJobBuildable) {
    stage('cENM Add Network') {
        if (checkJobBuildable("cENM_Add_Network")) {
            def Cenm_Add_Network = build(
                job: "cENM_Add_Network",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'nodes_to_add_to_enm', value: env.nodes_to_add_to_enm),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'drop', value: env.drop),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Add_Network Job is disabled. So skipping"
        }
    }
}

return this
