def returnParametersForDsl() {
    return [OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfSpinnakerCenmAduCcdUpgradeJobs() {
    def listOfSpinnakerCenmAduCcdUpgradeJobs = []

    // === ADU CCD Upgrade Spinnaker Pipeline Updater ===
    listOfSpinnakerCenmAduCcdUpgradeJobs = listOfSpinnakerCenmAduCcdUpgradeJobs.plus('DSL/spinnakerpipeline/cenm/adu_ccd_upgrade/SpinnakerCenmAduCcdUpgradePipeline.groovy')

    // === Spinnaker ADU CCD Upgrade Pipeline Generator Updater ===
    listOfSpinnakerCenmAduCcdUpgradeJobs = listOfSpinnakerCenmAduCcdUpgradeJobs.plus('pipeline_generation/spinnaker/adu_ccd_upgrade/DSL/spinnakercenmaduccdupgradepipelineupdater/SpinnakerCenmAduCcdUpgradePipelineUpdater.groovy')

    return listOfSpinnakerCenmAduCcdUpgradeJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker ADU CCD Upgrade Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfSpinnakerCenmAduCcdUpgradeJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}