def callChildJob(checkJobBuildable) {
    stage('cENM Setup Workload VM') {
        if (checkJobBuildable("cENM_Setup_Workload_VM")) {
            def Cenm_Setup_Workload_VM = build(
                job: "cENM_Setup_Workload_VM",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'tor_utils_version', value: env.tor_utils_version),
                    string(name: 'drop', value: env.drop),
                    string(name: 'product_set_version', value: env.product_set_version),
                    string(name: 'test_phase', value: env.test_phase),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Setup_Workload_VM Job is disabled. So skipping"
        }
    }
}

return this
