def returnParametersForDsl() {
    return [REGULAR_SLAVES: env.REGULAR_SLAVES, OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfSpinnakerCenmRestoreJobs() {
    def listOfSpinnakerCenmRestoreJobs = []

    // === Spinnaker cENM Restore Pipeline Updater ===
    listOfSpinnakerCenmRestoreJobs = listOfSpinnakerCenmRestoreJobs.plus('DSL/spinnakerpipeline/cenm/restore/SpinnakerCenmRestorePipeline.groovy')

    // === Spinnaker cENM Restore Pipeline Generator Updater ===
    listOfSpinnakerCenmRestoreJobs = listOfSpinnakerCenmRestoreJobs.plus('pipeline_generation/spinnaker/restore/DSL/spinnakercenmrestorepipelineupdater/SpinnakerCenmRestorePipelineUpdater.groovy')

    return listOfSpinnakerCenmRestoreJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.REGULAR_SLAVES == null
                    }
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker cENM Restore Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfSpinnakerCenmRestoreJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}