def callChildJob(checkJobBuildable) {
    stage('cENM Add Nodes To Workload Pool') {
        if (checkJobBuildable("Cenm_Add_Nodes_To_Workload_Pool")) {
            def Cenm_Add_Nodes_To_Workload_Pool = build(
                job: "Cenm_Add_Nodes_To_Workload_Pool",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'nodes_to_add_to_workpool', value: env.nodes_to_add_to_workpool),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "Cenm_Add_Nodes_To_Workload_Pool Job is disabled. So skipping"
        }
    }
}

return this
