import jenkins.model.*

pipeline {

    agent {
        node {
            label SLAVE
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Initial Install on ${cluster_id}"
                    currentBuild.description = "<b>Drop = ${drop}<br>Product Set Version = ${cenm_product_set_version}<br>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Execute EMT Deployment State Change Script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/emt_deployment_state_change.sh ${WORKSPACE}/parameters.properties || exit 1"
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/intermediate_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('RNL cENM Initial Install') {
            when {
                expression {
                    env.is_dit_versioning_applied == "False"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Initial_Install")) {
                        def Cenm_Initial_Install = build(
                            job: "cENM_Initial_Install",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'deployment_mechanism', value: 'csar'),
                                string(name: 'integration_value_type', value: 'eric-enm-integration-production-values'),
                                string(name: 'drop', value: env.drop),
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'stage_area', value: 'ci_internal'),
                            ]
                        )
                    } else {
                        echo "cENM_Initial_Install Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('RNL New cENM Initial Install') {
            when {
                expression {
                    env.is_dit_versioning_applied == "True"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Initial_Install_New")) {
                        def Cenm_Initial_Install_New = build(
                            job: "cENM_Initial_Install_New",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'use_case', value: 'Install'),
                                string(name: 'Artifact_type', value: env.Artifact_type),
                                string(name: 'deployment_size', value: env.deployment_size),
                                string(name: 'orchestration_type', value: env.orchestration_type),
                                string(name: 'container_registry_type', value: env.container_registry_type),
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                            ]
                        )
                    } else {
                        echo "cENM_Initial_Install_New Job is disabled. So skipping"
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/intermediate_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}
