pipeline {
    agent {
        node {
            label PIPELINE_SLAVE
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.REGULAR_SLAVES == null
                    }
                    expression {
                        env.TE_DOCKER_SLAVES == null
                    }
                    expression {
                        env.PIPELINE_SLAVE == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }

        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage ('Find changed DSL scripts') {
            steps {
                script {
                    space_separated_list_of_standalone_jobs = returnListOfStandaloneJobs().join(' ')
                    difference_in_releases = sh(script: 'git diff --name-only HEAD^ HEAD | tr "\r\n" " "', returnStdout: true)
                }
                sh "sh ${WORKSPACE}/cicd/cicd_scripts/pipeline_generation_scripts/determine_list_of_dsl_seeds_and_json_files_to_update.sh \"${space_separated_list_of_standalone_jobs}\" \"${difference_in_releases}\""
                script {
                    def exists = fileExists "${WORKSPACE}/dsl_seed_jobs_to_build.txt"
                    if (exists) {
                        env.changed_dsl_files = readFile("${WORKSPACE}/dsl_seed_jobs_to_build.txt")
                    }
                }
            }
        }

        stage('Run modified DSL scripts') {
            when {
                expression {
                    env.changed_dsl_files != null
                }
            }
            steps {
                script {
                    changed_dsl_files_as_list = env.changed_dsl_files.split(' ')
                }
                jobDsl targets: changed_dsl_files_as_list.join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }

    post {
        failure {
            script {
                emailOnRelease(env.team_email, "Failed to generate DSL successfully based on DSL provided. Please contact team Bumblebee.")
            }
        }
        success {
            script {
                emailOnRelease(env.team_email, "New version of enm-release-cicd released and modified DSL generated successfully.")
            }
        }
    }
}

def returnParametersForDsl() {
    return [REGULAR_SLAVES: env.REGULAR_SLAVES, TE_DOCKER_SLAVES: env.TE_DOCKER_SLAVES, PIPELINE_SLAVE: env.PIPELINE_SLAVE, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfStandaloneJobs() {
    def listOfStandaloneJobs = []
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/workloadassertions/MtvWorkloadAssertions.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/cenmccdupgradeflow/CenmCcdUpgradeFlow.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/cenmcapoupgradeflow/CenmCapoUpgradeFlow.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/updateoverallstatusToBuildLog/UpdateOverallStatusToBuildLog.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/cenmdetermineburhookautomation/CenmDetermineBurHookAutomation.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedpipelines/geocenmprimarysitesetup/GeoCenmPrimarySiteSetup.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/cenmsysloginstall/CenmSyslogInstall.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/ombsphysicalbackup/OmbsPhysicalBackup.groovy')
    listOfStandaloneJobs = listOfStandaloneJobs.plus('DSL/seedchildjobs/cenmrfa250lcslogcollection/CenmRfa250LcsLogCollection.groovy')
    return listOfStandaloneJobs
}

def emailOnRelease(team_email, email_content) {
    if (env.changed_dsl_files != null) {
        def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} - ${currentBuild.currentResult}"
        emailext(body: email_content, mimeType: 'text/html', from: 'jenkins_monitoring@ericsson.com',
        subject: subject,
        to: team_email)
    }
}
