def callChildJob(checkJobBuildable) {
    stage('cENM Fetch Network') {
        if (checkJobBuildable("cENM_Fetch_Network")) {
            def Cenm_Fetch_Network = build(
                job: "cENM_Fetch_Network",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'product_set_version', value: env.product_set_version),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'force_arne_xml_creation', value: env.force_arne_xml_creation),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Fetch_Network Job is disabled. So skipping"
        }
    }
}

return this
