def returnParametersForDsl() {
    return [REGULAR_SLAVES: env.REGULAR_SLAVES, TE_DOCKER_SLAVES: env.TE_DOCKER_SLAVES, OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfCenmInstallJobs() {
    def listOfCenmInstallJobs = []
    // === UnInstall ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenmteardown/CenmUnInstall.groovy')

    // === II Deploy ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenminstall/spinoff/CenmInstall.groovy')

    // === Retrieve ENM Product Set Version ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/retrieveenmproductsetversion/RetrieveEnmProductSetVersion.groovy')

    // === II Deployment Setup ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenminstalldeploymentsetup/spinoff/CenmInstallDeploymentSetup.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/copyutilsrepotowlvm/CenmCopyUtilsRepoToWlvm.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/setupworkloadvm/CenmSetupWorkloadVm.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/ddcsetup/CenmDdcSetup.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/deploynsstestwareutilities/CenmDeployNssTestwareUtilities.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/addlicenses/CenmAddLicenses.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/updatetrustprofiles/CenmUpdateTrustProfiles.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/mediationsrestart/CenmMediationsRestart.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/addprepopulatednodesfunctional/CenmAddPrepopulatedNodesFunctional.groovy')

    // === II Acceptance Tests ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenminstallacceptancetests/spinoff/CenmInstallAcceptanceTests.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/uilauncherlinkverification/CenmUiLauncherLinkVerification.groovy')

    // === II NW & WL Setup ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenminstallnewtworkandworkloadsetup/spinoff/CenmInstallNetworkAndWorkloadSetup.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/cenmmultinrmfetchnetwork/CenmMultiNrmFetchNetwork.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/addnetwork/CenmAddNetwork.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/manageandsupervisenetwork/CenmManageAndSuperviseNetwork.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/managepmfunction/CenmManagePmFunction.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/addnodestoworkloadpool/CenmAddNodesToWorkloadPool.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/applypriority1workload/CenmApplyPriority1Workload.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/applypriority2workload/CenmApplyPriority2Workload.groovy')

    // === II Updater ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('pipeline_generation/cenm_install_deployment_setup/DSL/cenminstallpipelineupdater/spinoff/CenmInstallPipelineUpdater.groovy')

    return listOfCenmInstallJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.REGULAR_SLAVES == null
                    }
                    expression {
                        env.TE_DOCKER_SLAVES == null
                    }
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate cENM Install Deployment Setup and Functional Acceptance Tests Jobs') {
            steps {
                jobDsl targets: returnListOfCenmInstallJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}
