import jenkins.model.*

pipeline {

    agent {
        node {
            label SLAVE
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Deployment Setup on ${cluster_id}"
                    currentBuild.description = "<b>Drop = ${drop}<br>Product Set Version = ${product_set_version}<br>MT Utils Version = ${mt_utils_version}</b>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Execute EMT Deployment State Change Script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/emt_deployment_state_change.sh ${WORKSPACE}/parameters.properties || exit 1"
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/final_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('cENM Setup DDC') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Setup_DDC")) {
                        def Cenm_Setup_DDC = build(
                            job: "cENM_Setup_DDC",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'test_phase', value: 'RNL'),
                            ]
                        )
                    } else {
                        echo "cENM_Setup_DDC Job is disabled. So skipping"
                    }
                }
            }
        }

         stage('cENM Add Licenses') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Add_Licenses")) {
                        def Cenm_Add_Licenses = build(
                            job: "cENM_Add_Licenses",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'test_phase', value: 'RNL'),
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'drop', value: env.drop),
                                string(name: 'product_set_version', value: env.product_set_version),
                                string(name: 'deployment_type', value: 'cloud_native'),
                            ]
                        )
                    } else {
                        echo "cENM_Add_Licenses Job is disabled. So skipping"
                    }
                }
            }
        }

     // Waiting for the delivery of jira TORF-423197 to uncomment this stage
     // stage('cENM Node Cleanup') {
     //     steps {
     //          script {
     //              if (checkJobBuildable("RNL_ECN_vENM_Node_Cleanup")) {
     //                  def RNL_ECN_vENM_Node_Cleanup = build(
     //                      job: "RNL_ECN_vENM_Node_Cleanup",
     //                      propagate: true,
     //                      wait: true,
     //                  )
     //              } else {
     //                  echo "RNL_ECN_vENM_Node_Cleanup Job is disabled. So skipping"
     //              }
     //          }
     //      }
     //  }
    }

    post {
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/final_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }

}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}
