def returnParametersForDsl() {
    return [REGULAR_SLAVES: env.REGULAR_SLAVES, OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfSpinnakerCenmRollbackBackupJobs() {
    def listOfSpinnakerCenmRollbackBackupJobs = []

    // === Spinnaker cENM Rollback Backup Pipeline Updater ===
    listOfSpinnakerCenmRollbackBackupJobs = listOfSpinnakerCenmRollbackBackupJobs.plus('DSL/spinnakerpipeline/cenm/rollback_backup/SpinnakerCenmRollbackBackupPipeline.groovy')

    // === Spinnaker cENM Rollback Backup Pipeline Generator Updater ===
    listOfSpinnakerCenmRollbackBackupJobs = listOfSpinnakerCenmRollbackBackupJobs.plus('pipeline_generation/spinnaker/rollback_backup/DSL/SpinnakerCenmRollbackBackupPipelineUpdater.groovy')

    return listOfSpinnakerCenmRollbackBackupJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.REGULAR_SLAVES == null
                    }
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker cENM Rollback Backup Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfSpinnakerCenmRollbackBackupJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}