def callChildJob(checkJobBuildable) {
    stage('cENM Setup DDC') {
        if (checkJobBuildable("cENM_Setup_DDC")) {
            def Cenm_Setup_DDC = build(
                job: "cENM_Setup_DDC",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'test_phase', value: env.test_phase),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Setup_DDC Job is disabled. So skipping"
        }
    }
}

return this
