import jenkins.model.*

pipeline {

    agent {
        node {
            label SLAVE
        }
    }

    options {
        timestamps()
    }

    stages {

        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Cluster ID = ${cluster_id}"
                    currentBuild.description = "<b>Product Set Version = ${product_set_version}<br>MT Utils Version = ${mt_utils_version}<br>Node Packages Directory = ${node_packages_dir}</b>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Execute EMT Deployment State Change Script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/emt_deployment_state_change.sh ${WORKSPACE}/parameters.properties || exit 1"
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/intermediate_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('RNL cENM ECN MGW Download Package') {
            steps {
                script {
                    if (checkJobBuildable("RNL_ECN_MGW_Download_Package")) {
                        def Cenm_RNL_ECN_MGW_Download_Package = build(
                            job: "RNL_ECN_MGW_Download_Package",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'test_phase', value: 'RNL'),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'node_type', value: "MGW"),
                                string(name: 'node_packages_dir', value: env.node_packages_dir),
                                string(name: 'drop', value: env.drop),
                                string(name: 'product_set_version', value: env.product_set_version),
                            ]
                        )
                    } else {
                        echo "RNL_ECN_MGW_Download_Package Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('RNL cENM ECN Router6672 Download Package') {
            steps {
                script {
                    if (checkJobBuildable("RNL_ECN_Router6672_Download_Package")) {
                        def Cenm_RNL_ECN_Router6672_Download_Package = build(
                            job: "RNL_ECN_Router6672_Download_Package",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'test_phase', value: 'RNL'),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'node_type', value: "Router6672"),
                                string(name: 'node_packages_dir', value: env.node_packages_dir),
                                string(name: 'drop', value: env.drop),
                                string(name: 'product_set_version', value: env.product_set_version),
                            ]
                        )
                    } else {
                        echo "RNL_ECN_Router6672_Download_Package Job is disabled. So skipping"
                    }
                }
            }
        }

    }

    post {
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/intermediate_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}