import jenkins.model.*
def SLAVE_FINAL = null

node(SLAVE) {
  stage('Determine Slave'){
     if (env.is_network_type_STC == "true") {
        SLAVE_FINAL = STC_SLAVE
     } else {
        SLAVE_FINAL = SLAVE
     }
   }
}

pipeline {

    agent {
        node {
            label SLAVE_FINAL
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Initial Install on ${cluster_id}"
                    currentBuild.description = "<b>Drop = ${drop}<br>Product Set Version = ${cenm_product_set_version}<br>MT Utils Version = ${mt_utils_version}</b>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE_FINAL}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/initial_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('cENM Send Confidence Level to Build log') {
            steps {
                setConfidenceLevelToSendToBuildLog('in_progress', 'in_progress','create', '', '');
            }
        }

        stage('cENM Clean Up Unsed Docker Images from Worker Node') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Cleanup_Unused_Docker_Images_From_WorkerNodes")) {
                        def CENM_Cleanup_Docker_images = build(
                            job: "cENM_Cleanup_Unused_Docker_Images_From_WorkerNodes",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'test_phase', value: env.test_phase)
                            ]
                        )
                    } else {
                        echo "cENM_Cleanup_Unused_Docker_Images_From_WorkerNodes Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('STC CDL cENM Initial Install') {
            when {
                expression {
                    env.is_network_type_STC == "true"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Initial_Install")) {
                        def Cenm_Initial_Install = build(
                            job: "cENM_Initial_Install",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'deployment_mechanism', value: env.deployment_mechanism),
                                string(name: 'integration_value_type', value: env.integration_value_type),
                                string(name: 'drop', value: env.drop),
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'stage_area', value: 'ci_internal'),
                                string(name: 'slave', value: SLAVE_FINAL),
                            ]
                        )
                    } else {
                        echo "cENM_Initial_Install Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Remove Workload Profiles') {
            steps {
                script {
                    if (env.deployment_mechanism == 'csar') {
                        if (checkJobBuildable("cENM_Remove_Profiles")) {
                            def CENM_Remove_Profiles = build(
                                job: "cENM_Remove_Profiles",
                                propagate: true,
                                wait: true,
                                parameters: [
                                    string(name: 'cluster_id', value: env.cluster_id),
                                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                                    string(name: 'remove_profiles_only', value: env.remove_profiles_only)
                                ]
                            )
                        } else {
                            echo "cENM_Remove_Profiles Job is disabled. So skipping"
                        }
                    }
                }
            }
        }

        stage('CDL cENM Initial Install') {
            when {
                expression {
                    env.is_network_type_STC == "false" && env.is_dit_versioning_applied == "False"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Initial_Install")) {
                        def Cenm_Initial_Install = build(
                            job: "cENM_Initial_Install",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'deployment_mechanism', value: 'csar'),
                                string(name: 'integration_value_type', value: 'eric-enm-integration-production-values'),
                                string(name: 'drop', value: env.drop),
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'stage_area', value: 'ci_internal'),
                            ]
                        )
                        env.job_link = Cenm_Initial_Install.absoluteUrl
                        env.console_output_url = sh(script: 'echo "Job Link is: ${job_link}"', returnStdout: true)
                        if (Cenm_Initial_Install.result != "SUCCESS") {
                            echo "ERROR : Cenm_Initial_Install failed. Failing the build!"
                            currentBuild.result = 'FAILURE'
                        }
                    } else {
                        echo "cENM_Initial_Install Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('CDL New cENM Initial Install') {
            when {
                expression {
                    env.is_network_type_STC == "false" && env.is_dit_versioning_applied == "True"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Initial_Install_New")) {
                        def Cenm_Initial_Install_New = build(
                            job: "cENM_Initial_Install_New",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'use_case', value: 'Install'),
                                string(name: 'Artifact_type', value: env.Artifact_type),
                                string(name: 'deployment_size', value: env.deployment_size),
                                string(name: 'orchestration_type', value: env.orchestration_type),
                                string(name: 'container_registry_type', value: env.container_registry_type),
                                string(name: 'drop', value: env.drop),
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                            ]
                        )
                        env.job_link = Cenm_Initial_Install_New.absoluteUrl
                        env.console_output_url = sh(script: 'echo "Job Link is: ${job_link}"', returnStdout: true)
                        if (Cenm_Initial_Install_New.result != "SUCCESS") {
                            echo "ERROR : cENM_Initial_Install_New failed. Failing the build!"
                            currentBuild.result = 'FAILURE'
                        }
                    } else {
                        echo "cENM_Initial_Install_New Job is disabled. So skipping"
                    }
                }
            }
        }

    }

    post {
        success {
            setConfidenceLevelToSendToBuildLog('in_progress', 'passed','update', env.job_link, '');
        }
        failure {
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', env.job_link, '');
        }
        aborted {
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', '', '');
        }
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/initial_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }
}

def setConfidenceLevelToSendToBuildLog(overall_status, confidence_level_status, build_action, job_link, allure_link) {
    script {
        if (env.publish_to_buildlog == 'YES') {
            if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                def Cenm_Send_Confidence_Level_To_Build_Log = build(
                    job: "cENM_Send_Confidence_Level_To_Build_Log",
                    propagate: false,
                    wait: false,
                    parameters: [
                        string(name: 'drop', value: env.drop),
                        string(name: 'to_ps', value: env.cenm_product_set_version),
                        string(name: 'build_log_action', value: build_action),
                        string(name: 'usecase_status', value: overall_status),
                        string(name: 'deployment', value: env.cluster_id),
                        string(name: 'test_phase', value: 'CDL'),
                        string(name: 'usecase', value: 'cENM-Deploy-II-CSAR'),
                        string(name: 'confidence_level', value: ''),
                        string(name: 'job_link', value: job_link ),
                        string(name: 'status', value: confidence_level_status),
                        string(name: 'timestamp', value: ''),
                        string(name: 'mt_utils_version', value: env.mt_utils_version)
                    ]
                )
            } else {
                echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}

