import jenkins.model.*

pipeline {

    agent {
        node {
            label SLAVE
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Deployment Setup on ${cluster_id}"
                    currentBuild.description = "<b>Product Set Version = ${product_set_version}<br>MT Utils Version = ${mt_utils_version}</b>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/intermediate_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('cENM Send Confidence Level') {
            steps {
                setConfidenceLevelToSend('in_progress');
            }
        }

        stage('cENM Copy Utils Repo To Environment') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Copy_Utils_Repo_To_Environment")) {
                        def Cenm_Copy_Utils_Repo_To_Environment = build(
                            job: "cENM_Copy_Utils_Repo_To_Environment",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                            ]
                        )
                    } else {
                        echo "cENM_Copy_Utils_Repo_To_Environment Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Setup DDC') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Setup_DDC")) {
                        def Cenm_Setup_DDC = build(
                            job: "cENM_Setup_DDC",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'test_phase', value: env.test_phase),
                            ]
                        )
                    } else {
                        echo "cENM_Setup_DDC Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Push Data To DDP') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Push_Data_To_DDP")) {
                        def Cenm_Push_Data_To_DDP = build(
                            job: "cENM_Push_Data_To_DDP",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'test_phase', value: env.test_phase),
                            ]
                        )
                    } else {
                        echo "cENM_Push_Data_To_DDP Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Deploy Tor Utilities Internal') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Deploy_Tor_Utilities_Internal")) {
                        def Cenm_Deploy_Tor_Utilities_Internal = build(
                            job: "cENM_Deploy_Tor_Utilities_Internal",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'tor_utils_version', value: env.tor_utils_version),
                                string(name: 'product_set_version', value: env.product_set_version),
                                string(name: 'test_phase', value: env.test_phase),
                            ]
                        )
                    } else {
                        echo "cENM_Deploy_Tor_Utilities_Internal Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Deploy NSS Testware Utilities') {
            steps {
                script {
                    if (checkJobBuildable("cENM_Deploy_NSS_Testware_Utilities")) {
                        def Cenm_Deploy_NSS_Testware_Utilities = build(
                            job: "cENM_Deploy_NSS_Testware_Utilities",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'cluster_id', value: env.cluster_id),
                                string(name: 'test_phase', value: env.test_phase),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'nss_utils_version', value: env.nss_utils_version),
                                string(name: 'product_set_version', value: env.product_set_version),
                            ]
                        )
                    } else {
                        echo "cENM_Deploy_NSS_Testware_Utilities Job is disabled. So skipping"
                    }
                }
            }
        }

        // Wait for confirmation from Ken to uncomment this when ready
        // stage('cENM Check Latest Time In DDP') {
        //     steps {
        //         script {
        //             if (checkJobBuildable("cENM_Check_Latest_Time_In_DDP")) {
        //                 def Cenm_Check_Latest_Time_In_DDP = build(
        //                     job: "cENM_Check_Latest_Time_In_DDP",
        //                     propagate: true,
        //                     wait: true,
        //                     parameters: [
        //                         string(name: 'cluster_id', value: env.cluster_id),
        //                         string(name: 'mt_utils_version', value: env.mt_utils_version),
        //                         string(name: 'test_phase', value: env.test_phase),
        //                         string(name: 'drop', value: env.drop),
        //                         string(name: 'ddp_upload_timeout_seconds', value: env.ddp_upload_timeout_seconds),
        //                         string(name: 'start_time', value: env.end_time),
        //                         string(name: 'end_time', value: env.end_time),
        //                     ]
        //                 )
        //             } else {
        //                 echo "cENM_Check_Latest_Time_In_DDP Job is disabled. So skipping"
        //             }
        //         }
        //     }
        // }
    }

    post {
        success {
            setConfidenceLevelToSend('passed');
        }
        failure {
            setConfidenceLevelToSend('failed');
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', '', '');
        }
        aborted {
            setConfidenceLevelToSend('failed');
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', '', '');
        }
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/intermediate_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }
}

def setConfidenceLevelToSend(confidence_level_status) {
    script {
        if (env.send_confidence_level == 'YES') {
            if (checkJobBuildable("cENM_Send_Confidence_Level")) {
                if (env.is_dit_versioning_applied == 'True') {
                    env.confidence_level_name = 'cENM-Deploy-UG-CSAR-Lite'
                } else {
                    env.confidence_level_name = 'cENM-Deploy-UG-Charts'
                }
                def Cenm_Send_Confidence_Level = build(
                    job: "cENM_Send_Confidence_Level",
                    propagate: false,
                    wait: false,
                    parameters: [
                        string(name: 'product_set_version', value: env.cenm_product_set_version),
                        string(name: 'confidence_level_name', value: env.confidence_level_name),
                        string(name: 'confidence_level_status', value: confidence_level_status),
                        string(name: 'mt_utils_version', value: env.mt_utils_version),
                    ]
                )
            } else {
                echo "cENM_Send_Confidence_Level Job is disabled. So skipping"
            }
        }
    }
}

def setConfidenceLevelToSendToBuildLog(overall_status, confidence_level_status, build_action, job_link, allure_link) {
    script {
        if (env.publish_to_buildlog == 'YES' && env.is_dit_versioning_applied == 'False') {
            if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                def Cenm_Send_Confidence_Level_To_Build_Log = build(
                    job: "cENM_Send_Confidence_Level_To_Build_Log",
                    propagate: false,
                    wait: false,
                    parameters: [
                        string(name: 'drop', value: env.drop),
                        string(name: 'to_ps', value: env.cenm_product_set_version),
                        string(name: 'build_log_action', value: 'final'),
                        string(name: 'usecase_status', value: overall_status),
                        string(name: 'deployment', value: env.cluster_id),
                        string(name: 'test_phase', value: 'MTE'),
                        string(name: 'usecase', value: 'cENM-Deploy-UG-Charts'),
                        string(name: 'confidence_level', value: ''),
                        string(name: 'job_link', value: job_link ),
                        string(name: 'status', value: confidence_level_status),
                        string(name: 'timestamp', value: ''),
                        string(name: 'mt_utils_version', value: env.mt_utils_version)
                    ]
                )
            } else {
                echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
            }
        } else {
            if (env.publish_to_buildlog == 'YES' && env.is_dit_versioning_applied == 'True') {
                if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                    def Cenm_Send_Confidence_Level_To_Build_Log = build(
                        job: "cENM_Send_Confidence_Level_To_Build_Log",
                        propagate: false,
                        wait: false,
                        parameters: [
                            string(name: 'drop', value: env.drop),
                            string(name: 'to_ps', value: env.cenm_product_set_version),
                            string(name: 'build_log_action', value: build_action),
                            string(name: 'usecase_status', value: overall_status),
                            string(name: 'deployment', value: env.cluster_id),
                            string(name: 'test_phase', value: 'MTE'),
                            string(name: 'usecase', value: 'cENM-Deploy-UG-CSAR-Lite'),
                            string(name: 'confidence_level', value: ''),
                            string(name: 'allure_link', value: allure_link ),
                            string(name: 'status', value: confidence_level_status),
                            string(name: 'timestamp', value: ''),
                            string(name: 'mt_utils_version', value: env.mt_utils_version)
                        ]
                    )
                } else {
                    echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
                }
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}
