def returnParametersForDsl() {
    return [REGULAR_SLAVES: env.REGULAR_SLAVES, TE_DOCKER_SLAVES: env.TE_DOCKER_SLAVES, OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfCenmInstallJobs() {
    def listOfCenmInstallJobs = []

    // === Retrieve Latest Green cENM Product Set Version ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/cenmretrievelatestgreencenmproductsetversion/CenmRetrieveLatestGreenCenmProductSetVersion.groovy')

    // === II Deploy ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenminstall/rnl/cenminstall/CenmInstall.groovy')

    // === Retrieve ENM Product Set Version ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/retrieveenmproductsetversion/RetrieveEnmProductSetVersion.groovy')

    // === II Deployment Setup ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedpipelines/cenminstall/rnl/cenminstalldeploymentsetup/CenmInstallDeploymentSetup.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/ddcsetup/CenmDdcSetup.groovy')
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('DSL/seedchildjobs/addlicenses/CenmAddLicenses.groovy')

    // === II Updater ===
    listOfCenmInstallJobs = listOfCenmInstallJobs.plus('pipeline_generation/cenm_rnl_install/DSL/cenminstallpipelineupdater/CenmInstallPipelineUpdater.groovy')

    return listOfCenmInstallJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.REGULAR_SLAVES == null
                    }
                    expression {
                        env.TE_DOCKER_SLAVES == null
                    }
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate cENM Install Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfCenmInstallJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}
