def callChildJob(checkJobBuildable) {
    stage('cENM Deploy Tor Utilities Internal') {
        if (checkJobBuildable("cENM_Deploy_Tor_Utilities_Internal")) {
            def cENM_Deploy_Tor_Utilities_Internal = build(
                job: "cENM_Deploy_Tor_Utilities_Internal",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                    string(name: 'tor_utils_version', value: env.tor_utils_version),
                    string(name: 'product_set_version', value: env.product_set_version),
                    string(name: 'test_phase', value: env.test_phase),
                    string(name: 'is_network_type_STC', value: env.is_network_type_STC),
                ]
            )
        } else {
            echo "cENM_Deploy_Tor_Utilities_Internal Job is disabled. So skipping"
        }
    }
}

return this