def returnParametersForDsl() {
    return [OPENSTACK_SLAVES: env.OPENSTACK_SLAVES, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfSpinnakerCenmAduCapoUpgradeJobs() {
    def listOfSpinnakerCenmAduCapoUpgradeJobs = []

    // === ADU CAPO Upgrade Spinnaker Pipeline Updater ===
    listOfSpinnakerCenmAduCapoUpgradeJobs = listOfSpinnakerCenmAduCapoUpgradeJobs.plus('DSL/spinnakerpipeline/cenm/adu_capo_upgrade/SpinnakerCenmAduCapoUpgradePipeline.groovy')

    // === Spinnaker ADU CAPO Upgrade Pipeline Generator Updater ===
    listOfSpinnakerCenmAduCapoUpgradeJobs = listOfSpinnakerCenmAduCapoUpgradeJobs.plus('pipeline_generation/spinnaker/adu_capo_upgrade/DSL/spinnakercenmaducapoupgradepipelineupdater/SpinnakerCenmAduCapoUpgradePipelineUpdater.groovy')

    return listOfSpinnakerCenmAduCapoUpgradeJobs
}

pipeline {
    agent {
        node {
            label OPENSTACK_SLAVES
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.OPENSTACK_SLAVES == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }
        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage('Generate Spinnaker ADU CAPO Upgrade Pipeline Jobs') {
            steps {
                jobDsl targets: returnListOfSpinnakerCenmAduCapoUpgradeJobs().join('\n'),
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }
}