pipeline {
    agent {
        node {
            label PIPELINE_SLAVE
        }
    }

    environment {
        DSL_CLASSPATH = 'DSL'
    }

    stages {
        stage ('Validate required parameters set') {
            when {
                anyOf {
                    expression {
                        env.PIPELINE_SLAVE == null
                    }
                    expression {
                        env.TEAM_EMAIL == null
                    }
                }
            }
            steps {
                error('Some required parameter(s) not set. Please supply a value for all required parameters')
            }
        }

        stage ('Default PERMISSION_GROUPS if null') {
            when {
                expression {
                    env.PERMISSION_GROUPS == null
                }
            }
            steps {
                script {
                    env.PERMISSION_GROUPS = 'authenticated'
                }
            }
        }

        stage ('Find changed DSL scripts') {
            steps {
                script {
                    space_separated_list_of_geo_jobs = returnListOfGeoInstallJobs().join(' ')
                    difference_in_releases = sh(script: 'git diff --name-only HEAD^ HEAD | tr "\r\n" " "', returnStdout: true)
                }
                sh "sh ${WORKSPACE}/cicd/cicd_scripts/pipeline_generation_scripts/determine_list_of_dsl_seeds_and_json_files_to_update.sh \"${space_separated_list_of_geo_jobs}\" \"${difference_in_releases}\""
                script {
                    def exists = fileExists "${WORKSPACE}/dsl_seed_jobs_to_build.txt"
                    if (exists) {
                        env.changed_dsl_files = readFile("${WORKSPACE}/dsl_seed_jobs_to_build.txt")
                    }
                }
            }
        }

        stage('Run modified DSL scripts') {
            when {
                allOf {
                    expression {
                        env.changed_dsl_files != null
                    }
                    expression {
                        env.changed_dsl_files.contains('DeploymentSetup')
                    }
                }
            }
            steps {
                jobDsl targets: 'DSL/seedpipelines/geoinstalldeploymentsetup/mtv/GeoInstallDeploymentSetup.groovy',
                    additionalParameters: returnParametersForDsl(),
                    additionalClasspath: env.DSL_CLASSPATH
            }
        }
    }

    post {
        failure {
            script {
                emailOnRelease(env.team_email, "Failed to generate DSL successfully based on DSL provided. Please contact team Bumblebee.")
            }
        }
        success {
            script {
                if (env.changed_dsl_files != null) {
                    if (env.changed_dsl_files.contains('DeploymentSetup') || env.changed_dsl_files.contains('SecondarySiteSetup')) {
                        emailOnRelease(env.team_email, "New version of enm-release-cicd released and modified DSL generated successfully.")
                    }
                    if (env.changed_dsl_files.contains('Scheduler')) {
                        emailOnRelease(env.team_email, "Please Re-Generate the Geo II scheduler jobs for your deployment using GEO_Initial_Install_Scheduler_Generator for latest changes.")
                    }
                }
            }
        }
    }
}

def returnParametersForDsl() {
    return [PIPELINE_SLAVE: env.PIPELINE_SLAVE, TEAM_EMAIL: env.TEAM_EMAIL, PERMISSION_GROUPS: env.PERMISSION_GROUPS]
}

def returnListOfGeoInstallJobs() {
    def listOfGeoInstallJobs = []
    listOfGeoInstallJobs = listOfGeoInstallJobs.plus('DSL/seedpipelines/geoinitialinstallscheduler/mtv/GeoInitialInstallScheduler.groovy')
    listOfGeoInstallJobs = listOfGeoInstallJobs.plus('DSL/seedpipelines/geoinstalldeploymentsetup/mtv/GeoInstallDeploymentSetup.groovy')
    listOfGeoInstallJobs = listOfGeoInstallJobs.plus('DSL/seedpipelines/geophysicalsecondarysitesetup/mtv/GeoPhysicalSecondarySetup.groovy')
    listOfGeoInstallJobs = listOfGeoInstallJobs.plus('DSL/seedpipelines/geophysicalprimarysitesetup/mtv/GeoPhysicalPrimarySiteSetup.groovy')
    return listOfGeoInstallJobs
}

def emailOnRelease(team_email, email_content) {
    def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} - ${currentBuild.currentResult}"
    emailext(body: email_content, mimeType: 'text/html', from: 'jenkins_monitoring@ericsson.com',
    subject: subject,
    to: team_email)
}
