import jenkins.model.*
def SLAVE_FINAL = null

node(SLAVE) {
  stage('Determine Slave'){
     if (env.is_network_type_STC == "true") {
        SLAVE_FINAL = STC_SLAVE
     } else {
        SLAVE_FINAL = SLAVE
     }
   }
}

pipeline {

    agent {
        node {
            label SLAVE_FINAL
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Rollback on ${cluster_id}"
                    currentBuild.description = "<b>Drop = ${drop}<br>Product Set Version = ${cenm_product_set_version}<br>MT Utils Version = ${mt_utils_version}</b>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Execute EMT Deployment State Change Script') {
            steps{
                script {
                    if (env.test_phase == 'RNL') {
                       sh "MTELoopScripts/pipeline_scripts/emt/emt_deployment_state_change.sh ${WORKSPACE}/parameters.properties || exit 1"
                    }
                }
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE_FINAL}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/initial_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('cENM Send Confidence Level to Build log') {
            steps {
                setConfidenceLevelToSendToBuildLog('in_progress', 'in_progress','create', '', '');
            }
        }

        stage('Resolve enm_iso_version mapped to Product Set') {
            steps {
                script {
                    if (env.test_phase == 'RNL') {
                        sh "sh MTELoopScripts/pipeline_scripts/retrieve_enm_iso_version.sh ${WORKSPACE}/parameters.properties || exit 1"
                    }
                }
            }
        }

        stage('Running Setup Script') {
            steps{
               sh "sh MTELoopScripts/pipeline_scripts/cenm_backup_setup.sh ${WORKSPACE}/parameters.properties ROLLBACK || exit 1"
            }
        }

        stage('Inject environment variables') {
            steps {
                script {
                    commonMethods.loadProperties("${WORKSPACE}/build.properties")
                }
            }
        }

        stage('STC cENM Rollback Flow') {
            when {
                expression {
                    env.is_network_type_STC == "true"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Rollback")) {
                        def cENM_Rollback = build(
                            job: "cENM_Rollback",
                            propagate: false,
                            wait: true,
                            parameters: [
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'backup_name', value: env.backup_name),
                                string(name: 'stage_area', value: env.stage_area),
                                string(name: 'drop', value: env.drop),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'deployment_mechanism', value: env.deployment_mechanism),
                                string(name: 'integration_value_type', value: env.integration_value_type),
                                string(name: 'slave', value: SLAVE_FINAL),
                            ]
                        )
                        env.job_link = cENM_Rollback.absoluteUrl
                        sh(script: 'echo "job_link=${job_link}" >> "artifact.properties"')
                        env.console_output_url = sh(script: 'echo "Job Link is: ${job_link}"', returnStdout: true)
                        if (cENM_Rollback.result != "SUCCESS") {
                            echo "ERROR : cENM_Rollback failed. Failing the build!"
                            currentBuild.result = 'FAILURE'
                        }
                    } else {
                        echo "cENM_Rollback Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Rollback Flow') {
            when {
                expression {
                    env.is_network_type_STC == "false" && env.is_dit_versioning_applied == "False"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Rollback")) {
                        def cENM_Rollback = build(
                            job: "cENM_Rollback",
                            propagate: false,
                            wait: true,
                            parameters: [
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'backup_name', value: env.backup_name),
                                string(name: 'stage_area', value: env.stage_area),
                                string(name: 'drop', value: env.drop),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'deployment_mechanism', value: env.deployment_mechanism),
                                string(name: 'integration_value_type', value: env.integration_value_type)
                            ]
                        )
                        env.job_link = cENM_Rollback.absoluteUrl
                        sh(script: 'echo "job_link=${job_link}" >> "artifact.properties"')
                        env.console_output_url = sh(script: 'echo "Job Link is: ${job_link}"', returnStdout: true)
                        if (cENM_Rollback.result != "SUCCESS") {
                            echo "ERROR : cENM_Rollback failed. Failing the build!"
                            currentBuild.result = 'FAILURE'
                        }
                    } else {
                        echo "cENM_Rollback Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('New cENM Rollback Flow') {
            when {
                expression {
                    env.is_network_type_STC == "false" && env.is_dit_versioning_applied == "True"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Rollback_New")) {
                        def cENM_Rollback_New = build(
                            job: "cENM_Rollback_New",
                            propagate: false,
                            wait: true,
                            parameters: [
                                string(name: 'Artifact_type', value: env.Artifact_type),
                                string(name: 'use_case', value: 'Rollback'),
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'deployment_size', value: env.deployment_size),
                                string(name: 'orchestration_type', value: env.orchestration_type),
                                string(name: 'container_registry_type', value: env.container_registry_type),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'backup_name', value: env.backup_name),
                                string(name: 'scope', value: 'ROLLBACK'),
                            ]
                        )
                        env.job_link = cENM_Rollback_New.absoluteUrl
                        sh(script: 'echo "job_link=${job_link}" >> "artifact.properties"')
                        env.console_output_url = sh(script: 'echo "Job Link is: ${job_link}"', returnStdout: true)
                        if (cENM_Rollback_New.result != "SUCCESS") {
                            echo "ERROR : cENM_Rollback_New failed. Failing the build!"
                            currentBuild.result = 'FAILURE'
                        }
                    } else {
                        echo "cENM_Rollback_New Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('Archive artifacts') {
            steps{
                script {
                    if (env.test_phase == 'RNL') {
                        archiveArtifacts artifacts: 'artifact.properties'
                    }
                }
            }
        }
    }

    post {
        success {
            setConfidenceLevelToSendToBuildLog('in_progress', 'passed','update', env.job_link, '');
        }
        failure {
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update',  env.job_link, '');
        }
        aborted {
            setConfidenceLevelToSendToBuildLog('failed', 'failed','update', '', '');
        }
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/initial_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }
}

def setConfidenceLevelToSendToBuildLog(overall_status, confidence_level_status, build_action, job_link, allure_link) {
    script {
        if (env.publish_to_buildlog == 'YES' && env.test_phase == 'MTE') {
            if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                if (env.is_dit_versioning_applied == 'True') {
                    env.usecase = 'cENM-Deploy-Rollback-CSAR-Lite'
                } else {
                    env.usecase = 'cENM-Deploy-Rollback-Charts'
                }
                def Cenm_Send_Confidence_Level_To_Build_Log = build(
                    job: "cENM_Send_Confidence_Level_To_Build_Log",
                    propagate: false,
                    wait: false,
                    parameters: [
                        string(name: 'drop', value: env.drop),
                        string(name: 'to_ps', value: env.cenm_product_set_version),
                        string(name: 'from_ps', value: env.from_ps),
                        string(name: 'build_log_action', value: build_action),
                        string(name: 'usecase_status', value: overall_status),
                        string(name: 'deployment', value: env.cluster_id),
                        string(name: 'test_phase', value: env.test_phase),
                        string(name: 'usecase', value: env.usecase),
                        string(name: 'confidence_level', value: ''),
                        string(name: 'job_link', value: job_link ),
                        string(name: 'status', value: confidence_level_status),
                        string(name: 'timestamp', value: ''),
                        string(name: 'mt_utils_version', value: env.mt_utils_version)
                    ]
                )
            } else {
                echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
            }
        }
        else {
            if (env.publish_to_buildlog == 'YES' && env.test_phase == 'CDL') {
                if (checkJobBuildable("cENM_Send_Confidence_Level_To_Build_Log")) {
                    def Cenm_Send_Confidence_Level_To_Build_Log = build(
                        job: "cENM_Send_Confidence_Level_To_Build_Log",
                        propagate: false,
                        wait: false,
                        parameters: [
                            string(name: 'drop', value: env.drop),
                            string(name: 'to_ps', value: env.cenm_product_set_version),
                            string(name: 'from_ps', value: env.from_ps),
                            string(name: 'build_log_action', value: build_action),
                            string(name: 'usecase_status', value: overall_status),
                            string(name: 'deployment', value: env.cluster_id),
                            string(name: 'test_phase', value: env.test_phase),
                            string(name: 'usecase', value: 'cENM-Deploy-Rollback-CSAR'),
                            string(name: 'confidence_level', value: ''),
                            string(name: 'job_link', value: job_link ),
                            string(name: 'status', value: confidence_level_status),
                            string(name: 'timestamp', value: ''),
                            string(name: 'mt_utils_version', value: env.mt_utils_version)
                        ]
                    )
                } else {
                    echo "cENM_Send_Confidence_Level_To_Build_Log Job is disabled. So skipping"
                }
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}