import jenkins.model.*
def SLAVE_FINAL = null

node(SLAVE) {
  stage('Determine Slave'){
     if (env.is_network_type_STC == "true") {
        SLAVE_FINAL = STC_SLAVE
     } else {
        SLAVE_FINAL = SLAVE
     }
   }
}

pipeline {

    agent {
        node {
            label SLAVE_FINAL
        }
    }

    options {
        timestamps()
    }

    stages {
        stage('Set build name and description') {
            steps {
                script {
                    currentBuild.displayName = "Rollback Backup on ${cluster_id}"
                    currentBuild.description = "<b>Product Set Version = ${cenm_product_set_version}<br>MT Utils Version = ${mt_utils_version}</b>"
                }
            }
        }

        stage('Load common methods') {
            steps {
                script {
                    commonMethods = load("${env.WORKSPACE}/Jenkinsfiles/common_methods/CommonMethods.groovy")
                }
            }
        }

        stage('Writing Parameters to parameters.properties') {
            steps {
                script {
                    commonMethods.exportEnvVariablesToFile("parameters.properties")
                }
            }
        }

        stage('Downloading MT Utils Pipeline Scripts') {
            steps {
                script {
                    commonMethods.downloadMtUtils()
                }
            }
        }

        stage('Storing Job Details in Slave') {
            steps {
                script {
                    def node_name = "${SLAVE_FINAL}"
                    def date = new Date()
                    sh " echo \" NODE_NAME : ${env.NODE_NAME} ; JOB_NAME : ${env.JOB_NAME} ; BUILD_NUMBER : ${env.BUILD_NUMBER} ; $date \" >> \"/home/lciadm100/jenkins/job_details.log\" "
                }
            }
        }

        stage('Execute EMT Deployment State Change Script') {
            steps{
                script {
                    if (env.test_phase == 'RNL') {
                       sh "MTELoopScripts/pipeline_scripts/emt/emt_deployment_state_change.sh ${WORKSPACE}/parameters.properties || exit 1"
                    }
                }
            }
        }

        stage('Execute EMT Pipeline script') {
            steps{
              sh "MTELoopScripts/pipeline_scripts/emt/jenkins/initial_build_setup.sh ${WORKSPACE}/parameters.properties initial || exit 1"
            }
        }

        stage('Execute setup script') {
            steps{
                sh "sh MTELoopScripts/pipeline_scripts/cenm_backup_setup.sh ${WORKSPACE}/parameters.properties ROLLBACK || exit 1"
            }
        }

        stage('Inject environment variables') {
            steps {
                script {
                    commonMethods.loadProperties("${WORKSPACE}/build.properties")
                }
            }
        }

        stage('cENM Rollback STC Backup Flow') {
            when {
                expression {
                    env.is_network_type_STC == "true"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Backup")) {
                        def Cenm_Backup = build(
                            job: "cENM_Backup",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'backup_name', value: env.backup_name),
                                string(name: 'backup_scope', value: 'ROLLBACK'),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'stage_area', value: env.stage_area),
                                string(name: 'deployment_mechanism', value: env.deployment_mechanism),
                                string(name: 'drop', value: env.drop),
                                string(name: 'BRO_DEFAULT_BACKUP_TYPE', value: env.BRO_DEFAULT_BACKUP_TYPE),
                                string(name: 'slave', value: SLAVE_FINAL),
                            ]
                        )
                    } else {
                        echo "cENM_Backup Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('cENM Rollback Backup Flow') {
            when {
                expression {
                    env.is_network_type_STC == "false" && env.is_dit_versioning_applied == "False"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Backup")) {
                        def Cenm_Backup = build(
                            job: "cENM_Backup",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'backup_name', value: env.backup_name),
                                string(name: 'backup_scope', value: 'ROLLBACK'),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'stage_area', value: env.stage_area),
                                string(name: 'BRO_DEFAULT_BACKUP_TYPE', value: env.BRO_DEFAULT_BACKUP_TYPE),
                                string(name: 'deployment_mechanism', value: env.deployment_mechanism),
                                string(name: 'drop', value: env.drop)
                            ]
                        )
                    } else {
                        echo "cENM_Backup Job is disabled. So skipping"
                    }
                }
            }
        }

        stage('New cENM Rollback Backup Flow') {
            when {
                expression {
                    env.is_network_type_STC == "false" && env.is_dit_versioning_applied == "True"
                }
            }
            steps {
                script {
                    if (checkJobBuildable("cENM_Backup_New")) {
                        def Cenm_Backup_New = build(
                            job: "cENM_Backup_New",
                            propagate: true,
                            wait: true,
                            parameters: [
                                string(name: 'environment_name', value: env.cluster_id),
                                string(name: 'backup_name', value: env.backup_name),
                                string(name: 'scope', value: 'ROLLBACK'),
                                string(name: 'mt_utils_version', value: env.mt_utils_version),
                                string(name: 'product_set_version', value: env.cenm_product_set_version),
                                string(name: 'Artifact_type', value: env.Artifact_type),
                                string(name: 'use_case', value: 'Backup'),
                                string(name: 'deployment_size', value: env.deployment_size),
                                string(name: 'orchestration_type', value: env.orchestration_type),
                                string(name: 'BRO_DEFAULT_BACKUP_TYPE', value: env.BRO_DEFAULT_BACKUP_TYPE),
                                string(name: 'container_registry_type', value: env.container_registry_type)
                            ]
                        )
                    } else {
                        echo "cENM_Backup_New Job is disabled. So skipping"
                    }
                }
            }
        }

    }

    post {
        always {
            script {
                sh "MTELoopScripts/pipeline_scripts/emt/jenkins/final_build_setup.sh ${WORKSPACE}/parameters.properties post_build || exit 1"
            }
        }
    }
}

def checkJobBuildable(jobName) {
    def isBuildable = Jenkins.instance.getItem(jobName).isBuildable();
    return isBuildable
}
