def callChildJob(checkJobBuildable) {
    stage('cENM Copy Utils Repo To Environment') {
        if (checkJobBuildable("cENM_Copy_Utils_Repo_To_Environment")) {
            def Cenm_Copy_Utils_Repo_To_Environment = build(
                job: "cENM_Copy_Utils_Repo_To_Environment",
                propagate: true,
                wait: true,
                parameters: [
                    string(name: 'cluster_id', value: env.cluster_id),
                    string(name: 'mt_utils_version', value: env.mt_utils_version),
                ]
            )
        } else {
            echo "cENM_Copy_Utils_Repo_To_Environment Job is disabled. So skipping"
        }
    }
}

return this
